### PR TITLE
feat: add BZIP2 (.bz2) support for reading fasta and fastq

### PR DESCRIPTION
**Pull request by nickzoic**
Adds "BZIP2" compression option for reading .fastq and .fasta files which happen to be compressed with BZIP2.

(Exon already supports this, this just makes that ability available in biobear)

### CODE REVIEW

**Comment by nickzoic** [comment]
G'day @tshauck does this PR look okay?  Keen to get it merged so I can support reading .bz2 files ...

**Comment by tshauck** [comment]
Hi @nickzoic, thanks for contributing this and apologies for the long delay!

I ran the tests, and it looks like there's an unrelated issue I'll need to fix, before this can merge. I'll try to take care if over the next couple of days and follow up here when I know more.

**Comment by nickzoic** [comment]
Oh good because I have no idea what that error is meant to be about!
I did get it to build the branch locally and confirm that it passes 'pytest' tests though (except the S3 ones)

**Comment by tshauck** [comment]
@nickzoic Thanks again for opening the PR! Would you mind rebasing your branch. I think then the test should be resolved and I can merge it. I could also apply the patch manually, but wouldn't maintain history as well in github.

**Comment by nickzoic** [comment]
I think I've now successfully wrestled git into doing what I meant :-)

**Review by tshauck — APPROVED** [review]

**Comment by tshauck** [comment]
@nickzoic Looks great, thanks! Merging then'll make a new biobear release.

**Comment by tshauck** [comment]
@nickzoic The new build should now be on pypi (https://pypi.org/project/biobear/0.23.2/) -- would you mind giving it a try whenever you have time. Thanks again for the PR!

**Comment by nickzoic** [comment]
Yep!  Upgraded to 0.23.2 via pypi, now it opens .fastq.bz2 and .fa.bz2 files no problem.  Thanks!

**Comment by tshauck** [comment]
Awesome, thanks!

**Pull request merged**
